export const LOGIN_ACTION = "LOGIN_ACTION";
export const LOGIN_SUCCESS_ACTION = "LOGIN_SUCCESS_ACTION";

export const SIGNUP_ACTION = "SIGNUP_ACTION";
export const SIGNUP_SUCCESS_ACTION = "SIGNUP_SUCCESS_ACTION";

export const SAVE_EMPLOYEES_ACTION = "SAVE_EMPLOYEES_ACTION";
export const SAVE_EMPLOYEES_SUCCESS_ACTION = "SAVE_EMPLOYEES_SUCCESS_ACTION";

export const DELETE_EMPLOYEES_ACTION = "DELETE_EMPLOYEES_ACTION";
export const DELETE_SUCCESS_EMPLOYEES_ACTION = "DELETE_SUCCESS_EMPLOYEES_ACTION";

export const GET_EMPLOYEES_ACTION = "GET_EMPLOYEES_ACTION";
export const GET_EMPLOYEES_SUCCESS_ACTION = "GET_EMPLOYEES_SUCCESS_ACTION";

export const API_ERROR = "API_ERROR";
export const UNAUTHORIZED_ACTION = "UNAUTHORIZED_ACTION";
export const SAVE_USER_ACTION = "SAVE_USER_ACTION";